name: App deployment pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (uat, prod)'
        required: true
        type: choice
        options:
          - uat
          - prod

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run static code analysis
        run: npm install eslint && npx eslint .

      - name: Run vulnerability scan
        run: npm audit --audit-level=moderate

      - name: Run tests
        run: |
          npm run build --if-present
          npm start &
          sleep 5
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: src/release.zip

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/feature/')
    environment:
      name: 'inchcape-technical-test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          

      - name: 'Deploy to Azure Web App (BR)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inchcape-app-br-dev'
          slot-name: 'Production'
          package: .

      - name: 'Deploy to Azure Web App (SEA)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inchcape-app-sea-dev'
          slot-name: 'Production'
          package: .

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/develop'
    environment:
      name: 'inchcape-technical-test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          

      - name: 'Deploy to Azure Web App (BR)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inchcape-app-br-test'
          slot-name: 'Production'
          package: .

      - name: 'Deploy to Azure Web App (SEA)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inchcape-app-sea-test'
          slot-name: 'Production'
          package: .

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.environment == 'uat'
    environment:
      name: 'inchcape-technical-test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          

      - name: Manual Approval
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          approvers: "eaarrll"

      - name: 'Deploy to Azure Web App (BR)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inchcape-app-br-uat'
          slot-name: 'Production'
          package: .

      - name: 'Deploy to Azure Web App (SEA)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inchcape-app-sea-uat'
          slot-name: 'Production'
          package: .
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.environment == 'prod'
    environment:
      name: 'inchcape-technical-test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          

      - name: Manual Approval
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          approvers: "eaarrll"

      - name: 'Deploy to Azure Web App (BR)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inchcape-app-br-prod'
          slot-name: 'Production'
          package: .

      - name: 'Deploy to Azure Web App (SEA)'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inchcape-app-sea-prod'
          slot-name: 'Production'
          package: .
