name: UAT Pipeline

on:
  push:
    branches:
      - 'release/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: src

    - name: Run tests
      run: npm test
      working-directory: src

    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: myapp-uat
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_UAT }}
        package: ${{ github.workspace }}/src

    - name: Package application
      run: |
        mkdir -p package
        zip -r package/app.zip src
      working-directory: .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-package
        path: package/app.zip

    - name: Trigger Testing Pipeline
      uses: actions/github-script@v4
      with:
        script: |
          const { owner, repo } = context.repo;
          const ref = 'refs/heads/main';
          const workflow_id = 'testing.yml';

          const response = await github.actions.createWorkflowDispatch({
            owner,
            repo,
            workflow_id,
            ref
          });

          console.log(response);

